---
redmine:
  api_key: xxx
  site: https://redmine.example.com

github:
  oauth_token: xxx
  user: username
  # avoid setting repo here!

# Map of:
# redmine user -> github user
user_map:
  johndoe: jdoemasterXX