---
redmine:
  api_key: xxx
  site: https://redmine.example.com

github:
  oauth_token: xxx
  user: username
  # avoid setting repo here!

  # To enable Github API preview for the issue import API:
  #headers:
  #  Accept: application/vnd.github.golden-comet-preview

# When you want to use the Github Import API
#github_api_import: true

# How the issue on Github should be prefixed
# Looks like: [PREFIX #1234] <subject>
#github_subject_prefix: 'Redmine'

# Map of:
# redmine user -> github user
user_map:
  johndoe: jdoemasterXX
